### PR TITLE
Port to Linux

### PR DESCRIPTION
**Pull request by jcdubois**
This is an initial port to Linux based on the windows source code.

This allows Linux to act as host and as a target.

### CODE REVIEW

**Comment by aamcampbell** [comment]
hank you for your contribution to Reliance Edge! Your changes are being reviewed by Datalight engineers, and we will update you soon.

**Comment by jcdubois** [comment]
Linux support should now be complete including the config tool

**Comment by jcdubois** [comment]
Hi Aaron.
When would it be reasonable to expect some feedback ?
I have more things to push but they would be based on the above changes.
Thanks.

**Comment by aamcampbell** [comment]
Jean,
We are doing our best to push your changes to GitHub before US Thanksgiving this week. As mentioned below, we have made some modifications, and we need to you sign a form before we can push them.

So that you are aware, any changes to Reliance Edge have to go through several internal procedures. Unfortunately this means it may take some time before we can update the master branch on GitHub. However, I believe we are almost ready to update it now. As you may have noticed, our commits to GitHub are part of an automated build process. This process cannot occur before the following steps are complete:

1. We need you to sign a copyright-assigment form so that we can use your code with commercial licensing (if you consent). We have sent this to the email address you registered on the Datalight website, let us know if you did not receive it.
2. Our engineers need to review your code and make changes to ensure it conforms to Datalight coding conventions and that it integrates well with our commercial package.

We are also working on a commercial-only release of Reliance Edge, but I believe we have worked it out so that this will not get in the way of pushing the Linux port to GitHub.

Concerning (2), we are almost finished with this effort. One major change you will notice is that we are combining much of the code from `os/win32/tools` and `os/linux/tools` and moving it to a common location. Internally, we have also been porting our commercial-only tools to Linux (a checker and an "image copy" tool).

**Comment by jcdubois** [comment]
Hello Aaron,

Thanks for the feeback.

I sent the agreement back to Kerri.

**Comment by aamcampbell** [comment]
We have now pushed the new Linux port up to GitHub, so I am going to close this request. Thanks again for your contribution!

As I mentioned before, you will notice several changes we made to accommodate the new Linux port. For example, the image builder and configuration tools have been moved to tools/, with port-specific image builder code in the os/[os]/tools folder. You may also note that all of the "host" projects (e.g. projects/linux/host) have been made generic so that a "make" command will successfully build them on either Linux or Windows.

We have added your name to the file [CREDITS.txt](https://github.com/datalightinc/reliance-edge/blob/master/CREDITS.txt) to acknowledge your effort.

Let me know if you want to further discuss anything concerning the new port. I'm not sure if you celebrate Thanksgiving in France, but I hope you have a great one either way! (Datalight will be offline for the holiday until next Monday.)

**Comment by jcdubois** [comment]
Happy Thanksgiving.

**Pull request closed without merging**
